services:
  - type: web
    name: "MoviesMosaic"
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn MoviesMosaic.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-actual-50-char-secret-key"
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "moviemosaic-1340.onrender.com"
